test/package/JSforceTestSuite/objects/JSforceTestSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ExecUsername__c</fullName>
        <label>Execution Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetTableNames__c</fullName>
        <label>Target Table Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JSforce Test Setting</label>
</CustomObject>

test-es5/package/JSforceTestSuite/objects/UpsertTable__c.object
<CustomObject>
    <label>UpsertTable</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UpsertTable</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test/package/JSforceTestSuite/classes/JSforceTestData.cls
@RestResource(urlMapping='/JSforceTestData/')
global class JSforceTestData {

    @HttpDelete
    global static void cleanupData() {
        cleanupData(System.now());
    }

    public static void cleanupData(Datetime dt) {
        JSforceTestSetting__c setting = JSforceTestSetting__c.getInstance(UserInfo.getUserId());
        if (setting != null) {
            String testUsername = setting.ExecUsername__c;
            String targetTableNames = setting.TargetTableNames__c;
            if (targetTableNames == null) {
              targetTableNames = 'Lead,Opportunity,Contact,Account,UpsertTable__c';
            }
            String[] tableNames = targetTableNames.split(',');
            for (String table : tableNames) {
                String soql = 'SELECT Id FROM ' + table + ' WHERE CreatedBy.Username = \'' + testUsername + '\' AND CreatedDate < ' + dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
                delete Database.query(soql);
            }
        }
    }
}