test/package/JSforceTestSuite/objects/JSforceTestSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ExecLatch__c</fullName>
        <label>Execution Latch</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ExecUsername__c</fullName>
        <label>Execution Username</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TargetTableNames__c</fullName>
        <label>Target Table Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>JSforce Test Setting</label>
</CustomObject>

test/package/JSforceTestSuite/classes/JSforceTestUtil.cls
public class JSforceTestUtil {

    private static JSforceTestSetting__c getTestSetting() {
        JSforceTestSetting__c setting = JSforceTestSetting__c.getOrgDefaults();
        if (setting == null) { setting = new JSforceTestSetting__c(ExecUsername__c=UserInfo.getUserName()); }
        return setting;
    }

    public static Boolean lockTestSession() {
        JSforceTestSetting__c setting = getTestSetting();
        Datetime now = System.now();
        if (setting.ExecLatch__c != null && setting.ExecLatch__c > now.addMinutes(-10)) {
            return false;
        }
        setting.ExecLatch__c = now;
        upsert setting;
        cleanupData();
        return true;
    }

    public static Boolean unlockTestSession() {
        JSforceTestSetting__c setting = getTestSetting();
        setting.ExecLatch__c = null;
        upsert setting;
        cleanupData();
        return true;
    }

    public static void cleanupData() {
        cleanupData(System.now());
    }    

    public static void cleanupData(Datetime dt) {
        JSforceTestSetting__c setting = JSforceTestSetting__c.getInstance(UserInfo.getUserId());
        if (setting != null) {
	        String testUsername = setting.ExecUsername__c;
            String targetTableNames = setting.TargetTableNames__c;
            String[] tableNames = targetTableNames.split(',');
            for (String table : tableNames) {
                String soql = 'SELECT Id FROM ' + table + ' WHERE CreatedBy.Username = \'' + testUsername + '\' AND CreatedDate < ' + dt.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
            	delete Database.query(soql);
            }
        }
    }
}