test-es5/package/JSforceTestSuite/objects/UserPool__c.object
<CustomObject>
    <fields>
        <fullName>CheckedOutAt__c</fullName>
        <label>Checked Out At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CheckedOutBy__c</fullName>
        <label>Checked Out By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPooled__c</fullName>
        <formula>ISNULL(CheckedOutAt__c) || NOW() - CheckedOutAt__c &gt; 0.1/24</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Pooled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastCheckedOutAt__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Last Checked Out At</label>
        <type>DateTime</type>
    </fields>
    <label>User Pool</label>
    <nameField>
        <label>Username</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test-es5/package/JSforceTestSuite/classes/JSforceTestUserPool.cls
@RestResource(urlMapping='/JSforceTestUserPool/*')
global with sharing class JSforceTestUserPool {
    
    @HttpPost
    global static Map<String, String> checkout(String clientName) {
        UserPool__c[] userpools = [
            SELECT Id, Name FROM UserPool__c
            WHERE IsPooled__c = true
            ORDER BY LastCheckedOutAt__c ASC NULLS FIRST
            LIMIT 1
        ];
        if (userpools.size() == 0) {
            return null;
        }
        Id poolId = userpools[0].Id;
        userpools = [
            SELECT Id, Name FROM UserPool__c
            WHERE IsPooled__c = true
            AND Id = :poolId
            LIMIT 1
            FOR UPDATE
        ];
        if (userpools.size() == 0) {
            return null;
        }
        Datetime now = System.now();
        userpools[0].LastCheckedOutAt__c = now;
        userpools[0].CheckedOutAt__c = now;
        userpools[0].CheckedOutBy__c = clientName;
        update userpools;
        return new Map<String, String> {
            'username' => userpools[0].Name
        };
    }

    @HttpDelete
    global static void checkin() {
        RestRequest req = RestContext.request;
        String username = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        UserPool__c[] userpools = [
            SELECT Id, Name FROM UserPool__c
            WHERE Name = :username
            LIMIT 1
            FOR UPDATE
        ];
        if (userpools.size() == 0) {
            return;
        }
        userpools[0].CheckedOutAt__c = null;
        userpools[0].CheckedOutBy__c = null;
        update userpools;
    }
  
}